[package]
name = "lambert_w"
version = "0.4.1"
edition = "2021"
authors = ["Johanna Sörngård <jsorngard@gmail.com>"]
categories = ["mathematics"]
keywords = ["lambert_w", "product_log", "omega_function"]
description = "Fast and accurate evaluation of the Lambert W function by the method of T. Fukushima."
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JSorngard/lambert_w"

[dependencies]
fast_polynomial = { version = "0.2.0", optional = true }

[dev-dependencies]
approx = "0.5.1"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"
rand_pcg = "0.3.1"

[features]
default = ["24bits", "50bits"]
# Enables the more accurate function versions with 50 bits of accuracy.
50bits = []
# Enables the faster function versions with 24 bits of accuracy.
24bits = []
# Uses [Estrin's scheme](https://en.wikipedia.org/wiki/Estrin's_scheme) instead of [Horner's Method](https://en.wikipedia.org/wiki/Horner%27s_method) to evaluate the polynomials in the Padé approximants.
# While this results in more assembly instructions, they are mostly independent of each other, and this increases instruction level parallelism on modern hardware for a total performance gain of up to ~25%.
# May result in slight numerical instability, which can be mitigated if the target cpu has fused multiply-add instructions.
estrin = ["dep:fast_polynomial"]

[package.metadata.docs.rs]
# Document all features.
all-features = true

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1

[[bench]]
name = "random"
harness = false

[[bench]]
name = "fixed"
harness = false