[package]
name = "lambert_w"
version = "0.1.0"
edition = "2021"
authors = ["Johanna Sörngård <jsorngard@gmail.com>, Toshio Fukushima <Toshio.Fukushima@nao.ac.jp>"]
categories = ["mathematics"]
keywords = ["lambert_w", "product_log", "omega_function"]
description = "Fast and accurate evaluation of the Lambert W function by the method of T. Fukushima."
rust-version = "1.65.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JSorngard/lambert_w"

[dependencies]

[dev-dependencies]
approx = "0.5.1"