[package]
name = "lambert_w"
version = "0.1.0"
edition = "2021"
authors = ["Toshio Fukushima <Toshio.Fukushima@nao.ac.jp>, Johanna Sörngård <jsorngard@gmail.com>"]
categories = ["mathematics"]
keywords = ["lambert_w", "product_log", "omega_function"]
description = "Precise and fast computation of the Lambert W function."
rust-version = "1.65.0"

[dependencies]

[dev-dependencies]
approx = "0.5.1"