[package]
name = "lambert_w"
version = "0.1.0"
edition = "2021"
authors = ["Johanna Sörngård <jsorngard@gmail.com>"]
categories = ["mathematics"]
keywords = ["lambert_w", "product_log"]
description = "Fast and accurate approximations of the Lambert W function."

[dependencies]

[dev-dependencies]
approx = "0.5.1"