[package]
name = "lambert_w"
version = "0.1.1"
edition = "2021"
authors = ["Johanna Sörngård <jsorngard@gmail.com>"]
categories = ["mathematics"]
keywords = ["lambert_w", "product_log", "omega_function"]
description = "Fast and accurate evaluation of the Lambert W function by the method of T. Fukushima."
rust-version = "1.65.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JSorngard/lambert_w"

[dependencies]

[dev-dependencies]
approx = "0.5.1"

[features]
default = ["24", "50"]
# Enables the function versions with 50-bits of accuracy.
50 = []
# Enables the function versions with 24-bits of accuracy.
24 = []

# docs.rs-specific configuration. Taken from <https://stackoverflow.com/a/61417700/>.
[package.metadata.docs.rs]
# Document all features.
all-features = true
# Enable the docsrs configuration attribute on docs.rs
rustdoc-args = ["--cfg", "docsrs"]